[package]
name = "generic_cong_avoid"
version = "0.1.0"
authors = ["Akshay Narayan <akshayn@mit.edu>"]

[dependencies]
clap="2.29"
portus = "0.3.3"
slog = {version = "2"}
slog-async = "2"
slog-term = "2"
time="0.1"
